### ISSUE TITLE
Main table scrollbar out of view when sidepanel opened

### ISSUE THREAD

**Issue by jayrbolton** [flimflamjs/ff-dashboard#6]
The sidepanel seems to cover up the scrollbar of the main panel

**Comment by yutakahoulette-zz** [comment]
i think the only way to show the scrollbar is to decrease the main panel width to fit the remaining space - which i don't think is ideal since that scrunches the table in the main panel. the main panel is still scrollable even tho the scrollbar is not visible.

**Comment by jayrbolton** [comment]
I think it's okay
